Remove internal AES implementation and replace it with use of libcrypto
awesomized/libmemcached pull request #114
Opened 2021-06-25 10:58 UTC by TomasKorbar

Hi,
As we are planning to replace original libmemcached in Fedora with awesomized libmemcached
i want to propose replacement of internal AES implementation with use of openssl.
In my opinion it is safer and more maintainable to use cryptographic library.
All tests are passing.
Feel free to propose any change.

2021-06-25 12:54 UTC, remicollet commented
@TomasKorbar this break build with old openssl (such as 1.02k in RHEL-7)

Proposal
```
diff -up ./src/libhashkit/aes.cc.old ./src/libhashkit/aes.cc
--- ./src/libhashkit/aes.cc.old	2021-06-25 14:53:38.891064258 +0200
+++ ./src/libhashkit/aes.cc	2021-06-25 14:53:45.840043166 +0200
@@ -37,10 +37,10 @@ bool aes_initialize(const unsigned char
     return false;
   }
 
-  if (EVP_CIPHER_CTX_init(encryption_context) != 1 ||
-      EVP_EncryptInit_ex(encryption_context, EVP_aes_256_cbc(), NULL, key,
+  EVP_CIPHER_CTX_init(encryption_context);
+  EVP_CIPHER_CTX_init(decryption_context);
+  if (EVP_EncryptInit_ex(encryption_context, EVP_aes_256_cbc(), NULL, key,
                          aes_iv) != 1 ||
-      EVP_CIPHER_CTX_init(decryption_context) != 1 ||
       EVP_DecryptInit_ex(decryption_context, EVP_aes_256_cbc(), NULL, key,
                          aes_iv) != 1) {
     return false;

```

2021-06-28 07:34 UTC, m6w6 requested changes
Thank you!

Please see the inline comments.

2021-06-28 07:34 UTC, m6w6 commented on CMakeLists.txt
> +
- This should be optional, and the build should use the bundled implementation when libcrypto was not found.
- It should use the cmake module [FindOpenSSL](https://cmake.org/cmake/help/v3.21/module/FindOpenSSL.html) and lbhashkit should link against `OpenSSL::Crypto` if found.
- It should be located in `src/libhashkit/CMakeLists.txt`

2021-06-28 07:34 UTC, m6w6 commented on include/libhashkit-1.0/hashkit.h
> +
Should be `#ifdef`'d for optional support

2021-06-28 07:34 UTC, m6w6 commented on include/libhashkit-1.0/hashkit.h
>  };
This breaks the ABI, so either allocate a private struct and reuse `_key`, or this may only be targeted at v2.0

2021-06-28 07:34 UTC, m6w6 commented on include/libhashkit-1.0/hashkit.h
> +bool hashkit_initialize_encryption(hashkit_st *kit, const char *key, const size_t key_length);
We're way too far into the stability game, so changing the API for better names is not a good idea.

2021-06-28 07:34 UTC, m6w6 commented on src/libhashkit/CMakeLists.txt
> +target_link_libraries(libhashkit PUBLIC -lcrypto)
See the `FindOpenSSL` and `OpenSSL::Crypto` comment above.

2021-06-28 07:34 UTC, m6w6 commented on src/libmemcached/is.h
> +#define memcached_is_encrypted(__object)        ((__object)->hashkit.use_encryption)
I think this should be `(!!(__object)->hashkit._key)` or alike.

2021-06-28 07:34 UTC, m6w6 commented on src/libhashkit/aes.cc
> +    return false;
See comment from Remi: https://github.com/awesomized/libmemcached/pull/114#issuecomment-868479036

2021-07-02 08:40 UTC, TomasKorbar commented
Hi @m6w6 ,
I update pull request according to your review. What do you think about it now?

2021-07-09 06:17 UTC, TomasKorbar commented
@m6w6 Any update on this?

2021-07-09 06:28 UTC, m6w6 commented
Yes, the update is, that I'm currently camping and there have been thunderstorms tonight. 😉

2021-07-09 09:21 UTC, TomasKorbar commented
@m6w6 No pressure. Just wanted to keep this alive :) Enjoy your camping and i hope that the storms did not cause you any trouble.

2021-07-13 07:31 UTC, merged

2021-07-13 07:33 UTC, m6w6 commented
Merged, with a couple of fixes and simplifications, thank you!